version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-seed:
    build: 
      context: ./mongo-seed
    container_name: mongo-seed
    restart: "no"
    depends_on:
      - mongodb
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  movies-service:
    build:
      context: ./Movies
    container_name: movies-service
    restart: always
    ports:
      - '3004:3004'
    depends_on:
      - mongo-seed
    networks:
      - app-network

  recomendador-service:
    build:
      context: ./Recomendador
    container_name: recomendador-service
    restart: always
    ports:
      - '3003:3003'
    networks:
      - app-network
    depends_on:
      - mongo-seed
      - rabbitmq

  randommovies-service:
    build:
      context: ./RandomMovies
    container_name: randommovies-service
    restart: always
    ports:
      - '3002:3002'
    networks:
      - app-network
    depends_on:
      - mongo-seed

  historial-service:
    build:
      context: ./Historial
    container_name: historial-service
    restart: always
    ports:
      - '3001:3001'
    networks:
      - app-network
    depends_on:
      - mongo-seed
      - rabbitmq

  frontend:
    build:
      context: ./Frontend
    container_name: react-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - mongo-seed


volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
